#!/bin/sh

aclocal --force -I . \
&& autoheader --force -I . \
&& automake --foreign --add-missing --copy \
&& autoconf --force -I . 

if test -x ./config.status; then 
    ./config.status --recheck
fi
